import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} min-h-svh bg-background font-sans antialiased`}>
        <Providers>
          <div className="relative flex min-h-svh flex-col bg-background">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
